version: "3.9"

services:
  asr-infer:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: oblivion208/asr-infer:0.1.0-dev
    container_name: asr-infer
    tty: true
    ipc: "host"
    ports:
      - 8000:8000
      - 8888:8888
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    working_dir: /app
    volumes:
      - ../:/app
    command: bash
