version: "3.9"

services:
  asr-infer:
    build:
      context: .
      dockerfile: Dockerfile
    image: oblivion208/asr-infer:0.1.0
    container_name: asr-infer
    tty: true
    ipc: "host"
    ports:
      - 8000:8000
      - 8888:8888
    working_dir: /app
    volumes:
      - ../:/app
    command: bash
