# Stage 1: Builder/Compiler
FROM pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime

# Update and install packages
RUN apt update && \
    apt install --no-install-recommends -y gcc gcc-multilib build-essential git && \
    apt clean && rm -rf /var/lib/apt/lists/*

# Install dependencies
COPY requirements.txt /
RUN pip3 install --no-cache-dir --upgrade pip && \
    pip3 install --no-cache-dir --user -r /requirements.txt
