# Stage 1: Builder/Compiler
FROM python:3.10-slim AS compile-image

# Update and install packages
RUN apt update && \
    apt install --no-install-recommends -y gcc gcc-multilib build-essential git && \
    apt clean && rm -rf /var/lib/apt/lists/*
# Install dependencies
COPY requirements.txt /
RUN pip3 install --no-cache-dir --upgrade pip && \
    pip3 install --no-cache-dir --user -r /requirements.txt
    
# RUN pip3 uninstall -y onnxruntime ort-nightly && \
#     pip3 install --no-cache-dir --user ort-nightly==1.16.0.dev20230629002 --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/ORT-Nightly/pypi/simple/

# Stage 2: Runtime
FROM python:3.10-slim AS runtime-image
COPY --from=compile-image /root/.local /root/.local
# Environment Setup
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Shanghai \
    PATH=/root/.local/bin:$PATH \
    PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
